datasets:
  indicadores_aneel:
    name: "indicadores_aneel"
    source_type: "http"
    url: "https://dadosabertos.aneel.gov.br/dataset/d5f0712e-62f6-4736-8dff-9991f10758a7/resource/4493985c-baea-429c-9df5-3030422c71d7/download/indicadores-continuidade-coletivos-2020-2029.csv"
    format: "csv"
    load_strategy: "full_refresh"
    partition_by: []
    csv_options:
      separator: ";"
      encoding: "latin-1"
      infer_schema_length: 10000
    required_columns: []
    raw_path: "data/raw/aneel/indicadores_aneel"
    bronze_path: "data/bronze/aneel/indicadores_aneel"